filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/sample_logs/sample.log

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "filebeat-%{+yyyy.MM.dd}"

setup.kibana:
  host: "http://kibana:5601"
